import { ACCOUNT_ASSISTANT_ROLE, ACCOUNT_EXECUTIVE_ROLE, ACCOUNT_RECEIVABLE_ROLE, GENERAL_MANAGER_ROLE, HEAD_OF_ACCOUNTS_ROLE, HEAD_OF_MARKETING_ROLE, HEAD_OF_PROCUREMENT_ROLE, MARKETING_EXECUTIVE_ROLE, OPERATION_TEAM_ROLE, PURCHASING_ASSISTANT_ROLE, SUPER_ADMIN_ROLE } from "../types/Common";

export const ROLES = [
  SUPER_ADMIN_ROLE,
  GENERAL_MANAGER_ROLE,
  HEAD_OF_MARKETING_ROLE,
  HEAD_OF_PROCUREMENT_ROLE,
  HEAD_OF_ACCOUNTS_ROLE,
  MARKETING_EXECUTIVE_ROLE,
  PURCHASING_ASSISTANT_ROLE,
  ACCOUNT_RECEIVABLE_ROLE,
  ACCOUNT_EXECUTIVE_ROLE,
  ACCOUNT_ASSISTANT_ROLE,
  OPERATION_TEAM_ROLE
];
