// export const SUPER_ADMIN = 'Super Admin';
// export const GENERAL_MANAGER = 'General Manager';
// export const HEAD_OF_MARKETING = 'Head of Marketing';
// export const HEAD_OF_PROCUREMENT = 'Head of Procurement';
// export const HEAD_OF_FINANCE_ACCOUNTS = 'Head of Finance & Accounts';
// export const MARKETING_EXECUTIVE = 'Marketing Executive/Marketing Assistant';
// export const PURCHASING_ASSISTANT = 'Purchasing Assistant';
// export const ACCOUNT_RECEIVABLE = 'Account Receivable';
// export const ACCOUNT_EXECUTIVE = 'Account Executive';
// export const ACCOUNT_ASSISTANT = 'Account Assistant';
// export const OPERATION_TEAM = 'Operation Team';

import { ACCOUNT_ASSISTANT_ROLE, ACCOUNT_EXECUTIVE_ROLE, ACCOUNT_RECEIVABLE_ROLE, GENERAL_MANAGER_ROLE, HEAD_OF_ACCOUNTS_ROLE, HEAD_OF_MARKETING_ROLE, HEAD_OF_PROCUREMENT_ROLE, MARKETING_EXECUTIVE_ROLE, OPERATION_TEAM_ROLE, PURCHASING_ASSISTANT_ROLE, SUPER_ADMIN_ROLE } from "../types/Common";

export const ROLES = [
  SUPER_ADMIN_ROLE,
  GENERAL_MANAGER_ROLE,
  HEAD_OF_MARKETING_ROLE,
  HEAD_OF_PROCUREMENT_ROLE,
  HEAD_OF_ACCOUNTS_ROLE,
  MARKETING_EXECUTIVE_ROLE,
  PURCHASING_ASSISTANT_ROLE,
  ACCOUNT_RECEIVABLE_ROLE,
  ACCOUNT_EXECUTIVE_ROLE,
  ACCOUNT_ASSISTANT_ROLE,
  OPERATION_TEAM_ROLE
];
