export type Bunker = {
  id: string,
  name: string,
  official_number: string,
  imo_number: string,
  flag: string,
  call_sign: string,
  net_tonnage: string,
  gross_tonnage: string,
  sdwt: string,
  loa: string,
  depth: string,
  capacity: string,
  created_at: any,
}